### PR TITLE
Support for internationalization of date formatting

### LINKED ISSUE #15: Add support for internationalization of date formatting

### PR DESCRIPTION
**Pull request by animosic**
This commit tries to resolve #15

### CODE REVIEW

**Comment by corylown** [comment]
I appreciate your pull request and the effort to add internationalization support to edtf-humanize.

Before I can merge this change into the develop branch I think it would be helpful to update the documentation in README.md to demonstrate how to use this feature. We also need to think through how the gem might use the host Rails application's locale setting instead of having to set it separately in the gem's configuration. Ideas about that?

There are a couple of other places in the application that likely need attention for more complete international support, such as the option to use translations rather than hardcoded configuration values for "unknown" and "circa" and " to " Maybe that can be handled as a separate issue.

Thank you!

**Comment by animosic** [comment]
At this point the support for I18n is not complete, as remarked in README.
The translation of Century and Decade need some thoughts to be done.

The commit about earlier and later prefix in set is a small addition of feature, that add also two values in configuration. As for these values, what's your idea? do you mean to move all of them to a locale file?

Thank you, and congratulations for the gem!

**Comment by corylown** [comment]
I think this is a good start. Yes, I was thinking that the application could set some default values in case a translation is missing, but otherwise use a locale file for all language that gets added to the dates when they're humanized. Something like what you've done for EDTF::Season.

Are you ready for me to merge this into the develop branch? We can create new issues for the other internationalization work that needs to happen.

**Comment by animosic** [comment]
Ok both for merge and new specific issues to be opened. Thanks!

**Pull request merged**
